openapi: 3.0.0
info:
  version: "1"
  title: Mission Planner
servers:
  - url: "http://localhost:9000"
paths:
  /:
    get: 
      operationId: rootpath
  /activity:
    get:
      summary: "Get an activity"
      operationId: getActivity
      tags:
        - activity
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: "Sample response: Details about an activity"
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Activity"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Activity:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
        notes:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
